title: PyPOFacets
description: A Python implementation of the Radar Cross-Section simulation, based on [POFacets](https://www.mathworks.com/matlabcentral/fileexchange/35861-pofacets4-1).
theme: jekyll-theme-cayman
